esphome:
  name: nuki-ble-lock
  friendly_name: Nuki BLE Lock

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: recommended

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "your-api-key-here"

ota:
  password: "your-ota-password-here"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nuki BLE Lock Fallback Hotspot"
    password: "your-fallback-password"

captive_portal:

# External libraries
external_components:
  - source:
      type: git
      url: https://github.com/YOUR_USERNAME/esphome-nuki-ble.git
      ref: main
    components: [nuki_ble]

# Nuki BLE Lock component
lock:
  - platform: nuki_ble
    id: nuki_lock
    device_name: "ESP32-Nuki"
    device_id: 12345678  # Replace with your Nuki device ID
    pin_code: "1234"     # Replace with your Nuki pin code (optional)
    
    # Sensors
    battery_level:
      name: "Nuki Battery Level"
      id: nuki_battery_level
    battery_voltage:
      name: "Nuki Battery Voltage"
      id: nuki_battery_voltage
    rssi:
      name: "Nuki RSSI"
      id: nuki_rssi
    
    # Binary sensors
    door_sensor:
      name: "Nuki Door"
      id: nuki_door
    keypad_sensor:
      name: "Nuki Keypad Battery"
      id: nuki_keypad_battery
    ring_sensor:
      name: "Nuki Ring to Open"
      id: nuki_ring
    
    # Text sensors
    lock_state_sensor:
      name: "Nuki Lock State"
      id: nuki_lock_state
    last_action_sensor:
      name: "Nuki Last Action"
      id: nuki_last_action
    
    # Buttons
    unlock_button:
      name: "Nuki Unlock"
      id: nuki_unlock_btn
    lock_button:
      name: "Nuki Lock"
      id: nuki_lock_btn
    unlatch_button:
      name: "Nuki Unlatch"
      id: nuki_unlatch_btn
    
    # Numbers
    auto_unlock_time_number:
      name: "Nuki Auto Unlock Time"
      id: nuki_auto_unlock_time
      min_value: 0
      max_value: 255
      step: 1
    
    # Switches
    auto_unlock_switch:
      name: "Nuki Auto Unlock"
      id: nuki_auto_unlock
    auto_lock_switch:
      name: "Nuki Auto Lock"
      id: nuki_auto_lock

# Button actions
button:
  - platform: template
    name: "Nuki Unlock Action"
    on_press:
      - lock.unlock: nuki_lock
  
  - platform: template
    name: "Nuki Lock Action"
    on_press:
      - lock.lock: nuki_lock
  
  - platform: template
    name: "Nuki Unlatch Action"
    on_press:
      - lock.unlock: nuki_lock
      - delay: 2s
      - lock.lock: nuki_lock

# Status LED
status_led:
  pin:
    number: GPIO2
    inverted: true

# Web server
web_server:
  port: 80
