name: Nuki BLE
description: ESPHome component for Nuki Smart Lock BLE communication
version: "1.0.0"
homeassistant_domain: lock
documentation: https://github.com/I-Connect/NukiBleEsp32
repository: https://github.com/I-Connect/NukiBleEsp32
issues: https://github.com/I-Connect/NukiBleEsp32/issues
platforms:
  - esp32
  - esp32s2
  - esp32s3
  - esp32c3
  - esp32h2
codeowners:
  - "@esphome/core"
requirements:
  espressif32: ">=4.0.0"
